version: '1.0'

stages:
  - clone
  - create

steps:
  clone:
    title: Cloning repository...
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    stage: clone

  create_pipeline:
    type: pipeline-trigger-merge
    title: Creating pipeline...
    arguments:
      DEBUG: true
      SPEC: specification.yaml
      ONLY_CHANGED: true
      TRIGGERS_SUBDIR: triggers
    stage: create